version: "3.8"

services:
  e-commerce:
    build:
      context: .
      dockerfile: Dockerfile
      target: development # Ensure this matches the stage name in the Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
    command: npm run dev
    ports:
      - "3000:3000"
